# Generated by Django 4.2.2 on 2023-06-07 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Interaction",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("interaction_date", models.DateField()),
                ("interaction_description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("country", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("DATED", "Dated"),
                            ("PENDING", "Pending"),
                            ("OFFER", "Offer"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("application_date", models.DateField()),
                ("post_url", models.URLField()),
                ("company_name", models.CharField(max_length=255)),
                ("job_title", models.CharField(max_length=255)),
                ("job_role_and_responsibilities", models.TextField()),
                ("job_requirements", models.TextField()),
                ("job_benefits", models.TextField()),
                ("notes", models.TextField()),
                (
                    "interactions",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.interaction",
                    ),
                ),
                (
                    "job_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.location",
                    ),
                ),
            ],
        ),
    ]
